FROM ruby:3.3.8-slim

# Rails app lives here
WORKDIR /rails

# Install packages needed for development
# chromium と chromium-driver を追加（システムテスト用）
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libjemalloc2 \
    libvips \
    libyaml-dev \
    nodejs \
    libpq-dev \
    postgresql-client \
    npm \
    pkg-config \
    curl \
    chromium \
    chromium-driver && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Yarnのグローバルパスを$PATHに追加
ENV PATH="/usr/local/npm-global/bin:$PATH"

# Install yarn
RUN npm install --global yarn

# Set environment variables
ENV RAILS_ENV="development"
ENV BUNDLE_PATH="/usr/local/bundle"

# Install gems
COPY Gemfile ./
COPY Gemfile.lock* ./
RUN bundle install

# Copy application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start server
CMD ["rails", "server", "-b", "0.0.0.0"]